### ISSUE TITLE
Bump the xmlsec version in Pypi

### ISSUE THREAD

**Issue by jindriago-scf** [mehcode/python-xmlsec#114]
Hi!

It's possible to update the version in PyPi to 1.3.5? What it needs to be done? Actually it's only until 1.3.3

Thx!

**Comment by carsongregory** [comment]
This would be appreciated! Thank you.

**Comment by chuyik** [comment]
Please bump the pip version to the latest thanks @mehcode

**Comment by hoefling** [comment]
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.
