### ISSUE TITLE
Upload Wheel releases to Pypi

### ISSUE THREAD

**Issue by HolgerPeters** [mehcode/python-xmlsec#117]
Hi

it seems the wheel files are not uploaded to pypi https://pypi.org/project/xmlsec/1.3.3/#files but this would be a great distribution channel, as it would allow pip to pull the binary releases directly from there instead of requiring the user to download them from the provided link.

**Comment by darakian** [comment]
+1 Please provide updates in channel

**Comment by hoefling** [comment]
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.
