### ISSUE TITLE
error: Microsoft Visual C++ 14.0 is required

### ISSUE THREAD

**Issue by daveisagit** [mehcode/python-xmlsec#118]
Hi,
I am trying without much success to install xmlsec on Windows 10 Python 3.7
The usual pip install xmlsec fails with 
`    Retrieving "https://ci.appveyor.com/api/buildjobs/hij3a6776pdv2007/artifacts/libxml2-2.9.4.win64.zip" to "build/extra\libxml2-2.9.4.win64.zip"`

So I am trying to install from your repo (as well as others)
I've installed Build Tools (2019) but's later than 14.0 so when I `pip install .`

I get
```
    building 'xmlsec' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
```

Have I missed something or does the source need to refer to later a build tools version?
I'm trying various options on VS installer to choose older 14.x versions

Finally got a compile to work, for anyone else following my path. I found the following links useful
For getting VS Build Tools options
https://www.scivision.co/python-windows-visual-c-14-required/

For dealing with the no rc.exe found error
https://stackoverflow.com/questions/43858836/python-installing-clarifai-vs14-0-link-exe-failed-with-exit-status-1158

I'll mark as closed

**Comment by hoefling** [comment]
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.
