### ISSUE TITLE
Could we get additional windows wheel builds?

### ISSUE THREAD

**Issue by squishysquid** [mehcode/python-xmlsec#122]
be nice to have one for python 37 and 38, I suppose 36 still has another year before eol, and I don't know enough about appveyor to say whether it supports it.

**Comment by hoefling** [comment]
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.
