### ISSUE TITLE
Looking for maintainers

### ISSUE THREAD

**Issue by mehcode** [mehcode/python-xmlsec#124]
:wave: 

I clearly haven't had time to maintain this nor do I see myself having time to give it attention in the future. 

@bgaifullin was doing a great job but it looks like he's gotten busy elsewhere as well.

**Comment by hoefling** [comment]
@mehcode I would volunteer - as I see it, the project is already stable and mature, the only real issue I've noticed so far is the platform-specific wheels missing. For that, I'd need upload access to PyPI though (as described in #123). Once this is resolved, the only major thing left is support for occasional new versions of `libxml`/`xmlsec` and new Python major releases. I could also refurbish the docs and maintain/enhance the test suite on demand, having lots of experience with both `sphinx` and `pytest`.

**Comment by mehcode** [comment]
Done. Thanks for stepping up. Sent you an invite for the repo. What's your PyPi username?

**Comment by hoefling** [comment]
Awesome, thanks!

> What's your PyPi username?

It's [hoefling](https://pypi.org/user/hoefling/), same as on GitHub.

**Comment by mehcode** [comment]
And done. You have PyPi access as well. Thanks again. Feel free to email or ping if you need help understanding some of the internals.

**Comment by hoefling** [comment]
@mehcode gladly! Right now I have an issue with 2FA on PyPI, once it is resolved, I'll prepare a 1.3.7 featuring prebuilt wheels for Windows.

As for the next planning, I'll try to work on a ~100% coverage before submitting any changes to the lib code (already set up [automatic reports to codecov](https://codecov.io/gh/mehcode/python-xmlsec)), but I expect those to remain minimal, like #125 (a fix to the segfault when accessing attributes of some constants). Of course, I'll be grateful for any PR review you or @bgaifullin will find time to do.

**Comment by bgaifullin** [comment]
Congratulations @hoefling. Also feel free to contact me or ping if you need help.
I will try to response as soon as possible.
