### ISSUE TITLE
AES-GCM support

### ISSUE THREAD

**Issue by pitbulk** [mehcode/python-xmlsec#138]
At xmlseclibs (PHP) I saw some work to provide [AES-GCM ](https://github.com/robrichards/xmlseclibs/commit/8d8e56ca7914440a8c60caff1a865e7dff1d9a5a). I wonder how complex is to include it as well at xmlsec.

**Comment by hoefling** [comment]
I think it shouldn't be hard; just adding another transform constant since `libxmlsec` already does the heavy lifting:

```c
#if XMLSEC_VERSION_HEX > $(calc hex of 1.2.27)
    PYXMLSEC_ADD_TRANSFORM_CONSTANT(TransformAes128Gcm, "AES128_GCM");
    PYXMLSEC_ADD_TRANSFORM_CONSTANT(TransformAes192Gcm, "AES192_GCM");
    PYXMLSEC_ADD_TRANSFORM_CONSTANT(TransformAes256Gcm, "AES256_GCM");
#endif
```

**Comment by hoefling** [comment]
@pitbulk if you can try out the `hoefling/xmlsec@aes-gcm`:

```sh
pip install git+https://github.com/hoefling/xmlsec.git@aes-gcm
```
and confirm it working, it would be great - I will try to come up with some tests in the meanwhile.

**Comment by freekvw** [comment]
I have tried this and can confirm it works. Would be nice to get it merged :-)
