### ISSUE TITLE
Question regarding xmlsec.SignatureContext.sign

### ISSUE THREAD

**Issue by nareshenoy** [mehcode/python-xmlsec#14]
Hi,
I just wanted to check if there is a way to force xmlsec.SignatureContext.sign to include the `<X509SubjectName>` and `<X509IssuerSerial>` tags while signing xml documents.

Right now, I'm doing this (most of the code is taken from the `test_sign_generated_template_pem_with_x509` method in `test_sign.py`)

``` python
    root_node       = etree.fromstring(xmlstr)

    signature_node  = xmlsec.template.create(root_node,
                                             xmlsec.Transform.EXCL_C14N,
                                             xmlsec.Transform.RSA_SHA1)

    root_node.append(signature_node)

    # Add the <ds:Reference/> node to the signature template.
    ref = xmlsec.template.add_reference(signature_node, xmlsec.Transform.SHA1)

    # Add the enveloped transform descriptor.
    xmlsec.template.add_transform(ref, xmlsec.Transform.ENVELOPED)

    # Add the <ds:KeyInfo/> and <ds:KeyName/> nodes.
    key_info = xmlsec.template.ensure_key_info(signature_node)
    xmlsec.template.add_x509_data(key_info)

    # Create a digital signature context (no key manager is needed).
    ctx = xmlsec.SignatureContext()

    # Load private key (assuming that there is no password).
    filename = 'public-pk.pem'
    key = xmlsec.Key.from_file(filename, xmlsec.KeyFormat.PEM, '<password>')

    assert key is not None

    # Load the certificate and add it to the key.
    filename = 'public-cert.pem'
    key.load_cert_from_file(filename, xmlsec.KeyFormat.PEM)

    # Set key name to the file name (note: this is just a test).
    key.name = os.path.basename(filename)

    # Set the key on the context.
    ctx.key = key 

    ctx.sign(signature_node)

```

Thanks,
Naresh

**Comment by mehcode** [comment]
You'd have to poke around `xmlsec` itself. This library is just a small wrapper around the C library.

**Comment by bgaifullin** [comment]
Hi. I think the following code should help.
``
signature_node  = xmlsec.template.create(root_node,
                                             xmlsec.Transform.EXCL_C14N,
                                             xmlsec.Transform.RSA_SHA1)
xmlsec.template. add_x509_data (xmlsec.template. ensure_key_info(signature_node))
``
more information about xmlsec.templates can be found here:
https://www.aleksey.com/xmlsec/api/xmlsec-templates.html#XMLSECTMPLKEYINFOADDKEYNAME

**Comment by mehcode** [comment]
@bgaifullin You have proved time and again that you know way more about `xmlsec` than I do. You're now a collaborator. Take it as you will.

**Comment by pitbulk** [comment]
:+1:

**Comment by bgaifullin** [comment]
thank you.

**Comment by bgaifullin** [comment]
@nareshenoy, Do you still need help?

**Comment by fedexin40** [comment]
Hello @bgaifullin we are having same issue right now. We tried using your suggestion but unfortunately:

```
xmlsec.template.add_x509_data(xmlsec.template. ensure_key_info(signature_node)) 
```

just adds the X509Certificate node and we also need the X509IssuerSerial, we found this template on xmlsec https://www.aleksey.com/xmlsec/api/xmlsec-templates.html#XMLSECTMPLX509DATAADDISSUERSERIAL but unfortunately seems its not currenty supported by python-xmlsec

**Comment by bgaifullin** [comment]
I will see how to this method to python-xmlsec

**Comment by bgaifullin** [comment]
Now, xmlsec has methods to add [issuer_serial](http://pythonhosted.org/xmlsec/modules/template.html#xmlsec.template.x509_data_add_issuer_serial) and [issuer_subject_name](http://pythonhosted.org/xmlsec/modules/template.html#xmlsec.template.x509_data_add_subject_name).
You can find details in [documentation](http://pythonhosted.org/xmlsec/)
