### ISSUE TITLE
Compiled with debug enabled since 1.3.7

### ISSUE THREAD

**Issue by victorpantoja** [mehcode/python-xmlsec#152]
Hi!

Every time the lib is loaded, I get lines like these:

```bash
[/tmp/pip-install-ij_mze58/xmlsec/src/constants.c:17 PyXmlSec_Transform__del__] 0x7f95083ffb70
[/tmp/pip-install-ij_mze58/xmlsec/src/constants.c:17 PyXmlSec_Transform__del__] 0x7f95083ffb90
[/tmp/pip-install-ij_mze58/xmlsec/src/constants.c:17 PyXmlSec_Transform__del__] 0x7f95083ffbb0
[/tmp/pip-install-ij_mze58/xmlsec/src/constants.c:17 PyXmlSec_Transform__del__] 0x7f95083ffbd0
```

I checked the C code, and it seems it was compile with `PYXMLSEC_ENABLE_DEBUG`. So, any chances to get rid of it? Or what else could I do?

```bash
$ pkg-config --cflags xmlsec1
-D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/usr/include/xmlsec1 -I/usr/include/libxml2
```

I'm running on Debian 10 with the following lib versions:

```bash
$ apt-cache policy libxmlsec1
libxmlsec1:
  Installed: 1.2.27-2
  Candidate: 1.2.27-2
  Version table:
 *** 1.2.27-2 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
$ apt-cache policy libxml2
libxml2:
  Installed: 2.9.4+dfsg1-7+b3
  Candidate: 2.9.4+dfsg1-7+b3
  Version table:
 *** 2.9.4+dfsg1-7+b3 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

This does not happen with version 1.3.3.

Thanks!

Victor

**Comment by hoefling** [comment]
Hi Victor, it looks like you've installed `xmlsec` via `pip`? You need to clear the `DEBUG` env var before installing. Also `pip` caches built wheels locally, so a simple reinstall will take the cached wheel that was prebuilt with debug mode on. Either find and remove the cached wheel first, or ignore cached wheels when installing.

### find and remove cached wheel, unset `DEBUG`, reinstall

```sh
$ find ~/Library/Caches/pip/wheels/ -name "xmlsec*.whl" -delete
$ unset DEBUG
$ pip install xmlsec
```

### unset `DEBUG`, reinstall ignoring cached wheels

```sh
$ unset DEBUG
$ pip install xmlsec --no-cache-dir
```

**Comment by victorpantoja** [comment]
Hi @hoefling 

It worked fine! This is a Django project so `DEBUG=1` is set as default. As our default for our local env is True, I'll just remove it from the env file.

Thank you so much for your quick reply!

best,
Victor
