### ISSUE TITLE
Linux Instalation - Wheel

### ISSUE THREAD

**Issue by juanlanuzaginvgate** [mehcode/python-xmlsec#157]
Hello, I am working on an application that runs in multiple environments (mostly linux distros) and it is not viable to install the system dependencies specified in the readme. 

Is it possible to install xmlsec through pip without having to manually install the native libraries?
I saw in [PR132](https://github.com/mehcode/python-xmlsec/pull/132/files) that static builds for linux are implemented but no wheels are published in pypi releases.

Thanks!

**Comment by hoefling** [comment]
Hi @juanlanuzaginvgate, you're right about that - I have implemented building `manylinux` fat wheels with all the dependencies linked statically in a single shared object, but not published them b/c of linking against OpenSSL and I don't have a reliable process of updating the wheels on critical OpenSSL updates. See also my reasoning in #109 comments. In the meantime, if you need `manylinux` wheels, you can build them yourself -- see the instructions I left in #81. it is pretty much easy to prebuild them once and reuse on subsequent installations, or upload them to your private PyPI index; this is what we currently do in the company I work at.

**Comment by juanlanuzaginvgate** [comment]
Thanks for the help @hoefling!
Prebuiling the wheels seem like the way to go.
