### ISSUE TITLE
xmlsec package installation on windows failing

### ISSUE THREAD

**Issue by pradyumnak** [mehcode/python-xmlsec#16]
I am trying to install xmlsec package on windows but it failing. I tried to use the pre-build binaries for the required packages of libxml2, libxslt but still its failing to install.  FOllowing are the minimal logs(otherwise it pretty long list)

constants.obj : warning LNK4217: locally defined symbol xmlSecNs imported in function initconstants
libxmlsec.lib(xmlenc.o) : warning LNK4217: locally defined symbol xmlMalloc imported in function xmlSecEncCtxXmlEncrypt
libxmlsec.lib(keysmngr.o) : warning LNK4217: locally defined symbol xmlMalloc imported in function xmlSecSimpleKeysStoreFindKey
libxmlsec.lib(base64.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(io.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(keyinfo.o) : warning LNK4217: locally defined symbol xmlMalloc imported in function xmlSecKeyInfoNodeRead
libxmlsec.lib(keys.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(transforms.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(xmltree.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(buffer.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(keysdata.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(xpath.o) : warning LNK4217: locally defined symbol xmlMalloc imported in function xmlSecXPathDataCreate
libxmlsec.lib(dl.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(nodeset.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(list.o) : warning LNK4049: locally defined symbol xmlMalloc imported
libxmlsec.lib(keys.o) : warning LNK4049: locally defined symbol xmlFree imported
libxmlsec.lib(xmlenc.o) : warning LNK4217: locally defined symbol xmlFree imported in function xmlSecEncCtxEncDataNodeRead

Can you please provide definite steps to install this package on windows?

**Comment by mehcode** [comment]
It looks like you're failing to install `xmlsec` itself (not this library). I'm not sure how to help you here. 

Ah.

It looks like there are windows pre-builts here: https://www.aleksey.com/xmlsec/download.html

**Comment by bgaifullin** [comment]
the windows installation does not work yet. 
Development is going on branch windows_build.

**Comment by bgaifullin** [comment]
fixed in 1.3.1
