### ISSUE TITLE
Flask debug=True causes TypeError with xmlsec

### ISSUE THREAD

**Issue by nwbreneman** [mehcode/python-xmlsec#18]
Hello,

Running a Flask app with debug=True (app.run(debug=True)) returns a TypeError when attempting to enable debugging for xmlsec:

xmlsec.enable_debug_trace(debug)

e.g. in https://github.com/onelogin/python3-saml/blob/master/src/onelogin/saml2/utils.py#L557

Using a 0 or 1 instead of True/False works correctly.

I am using xmlsec 0.3.3.

I was asked to open an issue here -- I originally reported with OneLogin but was asked to open one here:

https://github.com/onelogin/python3-saml/issues/5

**Comment by mehcode** [comment]
Seems like a quick fix that -- we just want to coerce the parameter to be boolean and then get 1 or 0. Currently we just hope you passed 1 or 0.

https://github.com/mehcode/python-xmlsec/blob/53436b375e0a64c2fd46ae198107c453e725422b/src/xmlsec/utils.pyx#L52

**Comment by bgaifullin** [comment]
fixed in #20
