### ISSUE TITLE
Provide wheel packages for Linux on PyPI

### ISSUE THREAD

**Issue by atodorov** [mehcode/python-xmlsec#186]
Is there are reason wheel packages for Linux to be missing from PyPI ? 

If there isn't a technical reason I am advocating for Linux wheel packages to be uploaded to PyPI (preferably upload one for the latest release as well).  

In my particular case we're building a Docker image which needs python3-saml (provides wheel) which in turn depends on xmlsec which pip3 tries to compile from source.  The environment inside the docker image is very limited and we don't have access to all of the required -devel libraries in order to builds from source (vendor provides xmlsec1.rpm but not xmlsec1-devel.rpm). 

Let me know how you feel about providing those packages on PyPI?

**Comment by hoefling** [comment]
Hi @atodorov, yes, the support of PEP 513 wheels was requested already; I have explained my reasoning [here](https://github.com/mehcode/python-xmlsec/issues/157#issuecomment-693254958). You can also roll out your own `manylinux2010` wheels using the instructions from [here](https://github.com/mehcode/python-xmlsec/issues/81#issuecomment-633230184).
