### ISSUE TITLE
Support for `xmlSecIORegisterCallbacks` etc. or equivalent

### ISSUE THREAD

**Issue by ch3pjw** [mehcode/python-xmlsec#187]
I'm trying port some C code to Python that uses `xmlsec` to sign both a SOAP envelope and an external XML document, which will eventually be bundled into a multipart MIME request. The existing C code uses `xmlSecIORegisterCallbacks` to handle fetching the data for the corresponding `<Reference URI="cid:[some_id]">` node in the template. My naive Python code/template results in `(1, 'failed to sign')`, and with `xmlsec.enable_debug_trace()` enabled, I get:
```
func=xmlSecDSigReferenceCtxProcessNode:file=xmldsig.c:line=1382:obj=unknown:subj=unknown:error=21:invalid node:actual=NULL; expected=DigestValue
func=xmlSecDSigCtxProcessReferences:file=xmldsig.c:line=752:obj=Reference:subj=xmlSecDSigReferenceCtxProcessNode:error=1:xmlsec library function failed:
func=xmlSecDSigCtxProcessSignatureNode:file=xmldsig.c:line=517:obj=unknown:subj=xmlSecDSigCtxProcessReferences:error=1:xmlsec library function failed:
func=xmlSecDSigCtxSign:file=xmldsig.c:line=291:obj=unknown:subj=xmlSecDSigCtxProcessSignatureNode:error=1:xmlsec library function failed:
```

It doesn't look like these Python expose any way to handle loading of external data, and I don't _think_ the `xmlsec.tree.add_ids()` function is what I want instead.

How should I go about using external references and/or adding the ability to do so? I can probably get some time to work on adding anything that's needed, with the caveat that C is not my first language.

**Comment by hoefling** [comment]
Done in #188. Thank you @ch3pjw!
