### ISSUE TITLE
install the xmlsec through pip install xmlsec failed.

### ISSUE THREAD

**Issue by honghh2018** [mehcode/python-xmlsec#201]
Hi guys,
     i try to install the xmlsec by pip install xmlsec, but  it failed and complaint about below error:
![image](https://user-images.githubusercontent.com/41668708/147846124-657d4de1-57aa-402a-815c-20bf4da356d3.png)

I check my xmlsec1 package that already installed in my system. it can show the version when  run the xmlsec1 --version

But i still get the error when pip install xmlsec.

the pkg-config showing below issue:
(py3) [root@localhost jumpserver-2.17.1]# pkg-config --cflags xmlsec1
Package xmlsec1 was not found in the pkg-config search path.
Perhaps you should add the directory containing `xmlsec1.pc'
to the PKG_CONFIG_PATH environment variable
Package 'xmlsec1', required by 'virtual:world', not found
#####
CENTOS8 platform
#####
how can i fix this issue?
Best,
hanhuihong

**Comment by hoefling** [comment]
Hi, you are probably missing the headers - please check the list of required packages [in the docs](https://xmlsec.readthedocs.io/en/stable/install.html#linux-centos).

**Comment by honghh2018** [comment]
Hi guys, 
    Thanks the reply,
     On the CENTOS8, i can not install the xmlsec1-devel and xmlsec1-openssl-devel through yum, the message showing below:
![image](https://user-images.githubusercontent.com/41668708/147871631-8009520f-eed7-45a7-bf99-db07c5acb90f.png)
    It was complaint about the xmlsec1-devel and xmlsec1-openssl-devel can not be found.
    how can i fix this issue?
    Hope you reply.
Best
hanhuihong
