### ISSUE TITLE
Support for python 3.10?

### ISSUE THREAD

**Issue by astrochun** [mehcode/python-xmlsec#204]
Thanks again for maintaining a very useful library that is often used for SAML SSO.

I noticed when installing `xmlsec` on CPython 3.10 that a wheel is not available:

```
Installed /opt/hostedtoolcache/Python/3.10.2/x64/lib/python3.10/site-packages/python3_saml-1.14.0-py3.10.egg
Reading http://github.com/mehcode/python-xmlsec/tarball/master
Searching for xmlsec>=1.3.12
Reading https://pypi.org/simple/xmlsec/
Downloading https://files.pythonhosted.org/packages/70/d7/83ac0d43bb92333c8ba3d9be97b85d1b[285]
...
Best match: xmlsec 1.3.12
Processing xmlsec-1.3.12.tar.gz
Writing /tmp/easy_install-bey4yd1m/xmlsec-1.3.12/setup.cfg
Running xmlsec-1.3.12/setup.py -q bdist_egg --dist-dir /tmp/easy_install-bey4yd1m/xmlsec-1.3.12/egg-dist-tmp-umgx26l1
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
WARNING: The wheel package is not available.
```

I understand that only 3.5 to 3.9 is supported. Are there plans to support for 3.10?

**Comment by Cielquan** [comment]
I second this. For my project I only use >=3.10.

Because of the missing wheel, it is tried to create one locally upon installation (xmlsec is no direct dependency for me). The wheel creation crashes (on windows) because "stdio.h" is missing, which in itself is a whole 'nother issue, I know.

**Comment by daveisagit** [comment]
I 3rd it 😂 or any advice on workarounds / self-compilation etc.

**Comment by Cielquan** [comment]
Depends on linux it was pretty easy to self-compile. On windows I was not able to get it to work.

So if you are on linux I may be able to help you.

**Comment by daveisagit** [comment]
Thanks, but I'm on Windows

**Comment by daveisagit** [comment]
Hi there 👋 wonderful codebase maintainers. Just letting you know I am still really looking forward to 3.10 support on this. ❤️

**Comment by mick88** [comment]
This is blocking my project from upgrading to 3.10 as there are no windows py310 binaries in the latest release

**Comment by kostasmarkakis** [comment]
Please upgrade for 3.10! 
we have a project with 3 major components and in one of them, xmlsec is the only library out of 35 that prohibits the upgrade of our platform to 3.10!

**Comment by swolfe2** [comment]
Would really love support for >=3.10! I have a hard requirement to use 3.10 at work, and would really love to be able to use xmlsec on a project.

**Comment by hoefling** [comment]
Hi all, I've uploaded windows wheels including 3.10 ones with the release of 1.3.13.

**Comment by swolfe2** [comment]
Can confirm! Thanks for that!
