### ISSUE TITLE
Symbol not found: _xmlSecDSigNs

### ISSUE THREAD

**Issue by cynddl** [mehcode/python-xmlsec#21]
I installed python-xmlsec on Mac OS X 10.10.5, using libxml2 2.9.3 and libxmlsec1 1.2.20.

However, I cannot `import libxmlsec` with both Python 2.7 and Python 3.4. I get the following ImportError:

> ImportError: dlopen(/usr/local/[…]/xmlsec/constants.so, 2): Symbol not found: _xmlSecDSigNs
>  Referenced from: /usr/local/[…]/xmlsec/constants.so
>  Expected in: flat namespace
> in /usr/local/[…]/xmlsec/constants.so

I tried compilling with both clang and gcc-4.9, but I still get this error. I'm not sure where it is coming from. [Someone else](https://github.com/wonnage/xmlsec-ruby/issues/2) experienced this with Ruby, but the solution proposed (remove and re-install libxml2 and libxmlsec1) doesn't work on my system.

**Comment by bgaifullin** [comment]
Please provide me the list of symbols that are exported from your version of xmlsec1.dylib
In case if xmlsec1.dylib has been installed with brew - path will be /usr/local/lib/libxmlsec1.dylib

nm -gU /usr/local/lib/libxmlsec1.dylib

**Comment by cynddl** [comment]
Here is the dump of the symbols lists from my system, with ``_xmlSecDSigNs`` at line 84:
https://gist.github.com/cynddl/9fbff472034d05f11a4e
> 0000000000031c10 S _xmlSecDSigNs

I indeed installed libxmlsec1 with homebrew.

If I look into the ``constants.so`` file from python-xmlsec, the list of symbols is only:
> 0000000000006a90 S ___pyx_module_is_main_xmlsec__constants
> 0000000000001940 T _initconstants

**Comment by bgaifullin** [comment]
it is ok, that constants.so contains only this methods.
Please also provide the output for next command:
otool -L constants.so

**Comment by cynddl** [comment]
So, ``constants.so`` only uses ``libSystem.B.dylib`` and ``libgcc_s.1.dylib``. Shouldn't it use ``libxmlsec1.dylib`` too?

``otool -L /Users/cynddl/.python-eggs/xmlsec-0.5.0-py2.7-macosx-10.10-x86_64.egg-tmp/xmlsec/constants.so``
> /Users/cynddl/.python-eggs/xmlsec-0.5.0-py2.7-macosx-10.10-x86_64.egg-tmp/xmlsec/constants.so:
>	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
>	/usr/local/Cellar/gcc/4.9.1/lib/gcc/x86_64-apple-darwin13.3.0/4.9.1/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)

**Comment by bgaifullin** [comment]
Yes. It should use libxmlsec1.dylib , Seems like it built without libxmlsec1.
Please try to execute the following command in python interpreter

>>> import pkgconfig
>>> config = pkgconfig.parse('xmlsec1-openssl')
>>> print(config['libraries'])

the output should be:
{'pthread', 'xmlsec1', 'crypto', 'xslt', 'dl', 'm', 'xml2', 'ltdl', 'z', 'xmlsec1-openssl', 'icucore'}

**Comment by cynddl** [comment]
Yes, the output is an only an empty ``set()``.

**Comment by bgaifullin** [comment]
Could you check output for 'xmlsec1' . In case if it was not empty I prepare patch to fix this issue.

**Comment by cynddl** [comment]
The output is also empty for ```'xmlsec1'```. Does that mean the issue is coming from _xmlsec1_ and not _python-xmlsec_?

**Comment by bgaifullin** [comment]
yes, need to check why xmlsec1 does not provide information about itself.

**Comment by bluekeyes** [comment]
I was running into this same problem and managed to fix it today by upgrading Brew (along with `libxml2` and `libxmlsec1`) to the latest version and installing the XCode command line tools (`xcode-select --install`). I think the XCode tools were the real fix - after installing them, I no longer had to set `C_INCLUDE_PATH` to build either.

I thought I had installed these before, but apparently they can be removed when upgrading between OS versions.

**Comment by bgaifullin** [comment]
@cynddl please check that this approach works for you.

**Comment by subssn21** [comment]
I was having all sorts of problems installing and following bluekeyes instructions fixed the issue:

```
xcode-select --install
brew upgrade
```

**Comment by bgaifullin** [comment]
@subssn21 thanks, I will update Readme according to this instructions

**Comment by bgaifullin** [comment]
updated instructions.
