### ISSUE TITLE
Fail install in Docker Ubuntu 22.04 with python 3.10

### ISSUE THREAD

**Issue by igallart** [mehcode/python-xmlsec#211]
root@366a6b631183:~# pip install xmlsec
Collecting xmlsec
  Downloading xmlsec-1.3.12.tar.gz (64 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.2/64.2 KB 1.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting lxml>=3.8
  Using cached lxml-4.8.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_24_x86_64.whl (7.0 MB)
Building wheels for collected packages: xmlsec
  Building wheel for xmlsec (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for xmlsec (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      running bdist_wheel
      running build
      running build_py
      package init file 'src/xmlsec/__init__.py' not found (or not a regular file)
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/xmlsec
      copying src/xmlsec/py.typed -> build/lib.linux-x86_64-3.10/xmlsec
      copying src/xmlsec/__init__.pyi -> build/lib.linux-x86_64-3.10/xmlsec
      copying src/xmlsec/constants.pyi -> build/lib.linux-x86_64-3.10/xmlsec
      copying src/xmlsec/tree.pyi -> build/lib.linux-x86_64-3.10/xmlsec
      copying src/xmlsec/template.pyi -> build/lib.linux-x86_64-3.10/xmlsec
      running build_ext
      error: Unable to invoke pkg-config.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for xmlsec
Failed to build xmlsec
ERROR: Could not build wheels for xmlsec, which is required to install pyproject.toml-based projects

**Comment by ajit7395** [comment]
How did you solve this issue ? 
I am trying to install xmlsec v1.3.12 in ubuntu 22.04 docker image with python3.7.3 and pip 22.2.1. As per the docs, the dependencies are installed.
But I'm still facing this issue.

**Comment by igallart** [comment]
Hello, I can't, thanks.
