### ISSUE TITLE
Cannot install on Windows 10

### ISSUE THREAD

**Issue by guidros** [mehcode/python-xmlsec#214]
I've tried to install 1.3.12 library version on windows 10 but the installation gives the following error: 
      fatal error C1047: The object or library file 'C:\Users\guidr\AppData\Local\Temp\pip-install-vb4p8xkh\xmlsec_c83a2796c6b84c61ae947515cf2ad097\build\tmp\libs\iconv-1.14.win64\lib\iconv_a.lib' it was created with a different compiler version than other objects, for example 'build\temp.win-amd64-cpython-310\Release\Users\guidr\AppData\Local\Temp\pip-install-vb4p8xkh\xmlsec_c83a2796c6b84c61ae947515cf2ad097\src\constants.obj'; Rebuild all objects and libraries with the same compiler
      LINK : fatal error LNK1257: code generation failed
      error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.32.31326\\bin\\HostX86\\x64\\link.exe' failed with exit code 1257

Anyone could help me for this issue?
Thanx

**Comment by hoefling** [comment]
The 1.3.13 has prebuilt windows wheel for Python 3.10, try those instead.
