### ISSUE TITLE
Upload wheels to PyPi

### ISSUE THREAD

**Issue by ryanlinnit-sky** [mehcode/python-xmlsec#215]
Hello, as you have github actions to build linux, mac, etc wheels, could they also be uploaded to PyPi so these platforms don't have to install additional OS packages to compile the xmlsec module.

Currently only Windows wheels are available on PyPi.

Thanks :)

**Comment by hoefling** [comment]
@ryanlinnit-sky unfortunately, not because the code is compiled against OpenSSL. See my comment in #109.
