### ISSUE TITLE
Segmentation fault when executing dsig_ctx.verify with Python3

### ISSUE THREAD

**Issue by pitbulk** [mehcode/python-xmlsec#23]
I tested and using Python2 works.

I was executing  [testValidateSign](https://github.com/onelogin/python3-saml/blob/master/tests/src/OneLogin/saml2_tests/utils_test.py#L706) from python3-saml and got a segmentation fault when executed
```
OneLogin_Saml2_Utils.validate_metadata_sign(xml_metadata_signed, cert, validatecert=True)
```
that internally executes:
```
manager = xmlsec.KeysManager()
manager.load_cert_from_memory(cert, xmlsec.KeyFormat.CERT_PEM, xmlsec.KeyDataType.TRUSTED)
dsig_ctx = xmlsec.SignatureContext(manager)
dsig_ctx.set_enabled_key_data([xmlsec.KeyData.X509])
dsig_ctx.verify(signature_node)
``` 
and this last command throw the segmentation fault.

If instead I executes
```
dsig_ctx = xmlsec.SignatureContext()
dsig_ctx.key = xmlsec.Key.from_memory(cert, xmlsec.KeyFormat.CERT_PEM, None)
dsig_ctx.set_enabled_key_data([xmlsec.KeyData.X509])
dsig_ctx.verify(signature_node)
```
or run Python2 instead of Python3, it works as expected

so something is wrong on Python3 with the use of the Manager and xmlsec.KeyDataType.TRUSTED
It used to work time ago.

I'm using
```
Python 3.4.3
....
lxml==3.5.0
xmlsec==0.5.0
```

I hope you will be able to reproduce and fix.

Best regards.

**Comment by bgaifullin** [comment]
@pitbulk this issue should be fixed in commit https://github.com/mehcode/python-xmlsec/commit/762bff6b07fc7a6434fa4ef1bf10069d541b9e02

Please could you check this issue in version from master branch?

**Comment by bgaifullin** [comment]
@mehcode do you upload new build on pypi with last fixes?

**Comment by mehcode** [comment]
Pushed 0.6.0 to pypi (sorry for the long delay and thanks a lot for the recent fixes @bgaifullin )

**Comment by pitbulk** [comment]
Is working with 0.6.0 version, thanks
