### ISSUE TITLE
Segmentation fault on decryption in 0.6.1 and Python3.5

### ISSUE THREAD

**Issue by yns88** [mehcode/python-xmlsec#28]
We experienced an issue very similar to https://github.com/mehcode/python-xmlsec/issues/23 in python3-saml (which has a requirement of xmlsec>=0.6.0) -- calls into xmlsec caused segmentation faults after the upgrade to 0.6.1, and a downgrade to 0.6.0 made the issue go away.

I think this may be a regression of that same issue that was closed in 0.6.0, though unfortunately I don't have any stacktraces showing the exact line of code in xmlsec where the segfault occurred.

**Comment by bgaifullin** [comment]
Hi. Could you please provide script or code which cause segmentation fault. This will help me to reproduce this issue on my side.
Thank you.

**Comment by yns88** [comment]
I'm sorry I can't give a more detailed trace, but the error occurs in this code in python3-saml (`OneLogin_Saml2_Response.__init__()`)
https://github.com/onelogin/python3-saml/blob/3659de8e4e9a11ec0683764b53e88acae6b2976b/src/onelogin/saml2/response.py#L26

I believe it's likely that this function call is where the issue occurs:
https://github.com/onelogin/python3-saml/blob/3659de8e4e9a11ec0683764b53e88acae6b2976b/src/onelogin/saml2/utils.py#L629

**Comment by mehcode** [comment]
@yns88 Here are the changes: https://github.com/mehcode/python-xmlsec/compare/v0.6.0...master

I messed up here as for some reason I thought that only my last commit was new (I forget that you're working on this @bgaifullin; I need to give you pypi access so you can release as well) and just made a patch release.

**Comment by mehcode** [comment]
@yns88 Do you have a reproducible test case you could give us? Or bisect through that changeset and figure out which changeset it is?

These sorts of errors are plain hard to debug without reproduction.

**Comment by pitbulk** [comment]
Here:
https://travis-ci.org/onelogin/python3-saml/jobs/167668391

**Comment by bgaifullin** [comment]
Hi, @pitbulk I cannot reproduce this issue on ubuntu-16 with xmlsec 0.6.1 and libxmlsec 1.2.20 and 1.2.21. Could you add command to your travis.yml file to dump libxmlsec1 version. Seems like this issue is related to version of libxmlsec1

**Comment by bgaifullin** [comment]
the command is 'apt-cache show libxmlsec1'

**Comment by pitbulk** [comment]
Here is: https://travis-ci.org/onelogin/python3-saml/jobs/168212377

**Comment by pitbulk** [comment]
libxml2  Version: 2.8.0+dfsg1-5ubuntu2.2~precise1
libxmlsec1 Version: 1.2.14-1.2build1

**Comment by bgaifullin** [comment]
@pitbulk thanks, I can investigate this issue only at the weekend.

**Comment by pitbulk** [comment]
Ok, let me know if you need anything else.

**Comment by bgaifullin** [comment]
@pitbulk,
I cannot reproduce this fail on ubuntu12.04 with libxmlsec1 version 1.2.14-1.2build1.
Lets try to print backtrace when tests fails:
There is some instructions, how to do this:

Put the following in backtrace
```
backtrace
quit
```

Put this in a script called seg_wrapper.sh
```
#!/bin/bash
ulimit -c unlimited
"$@"
if [[ $? -eq 139 ]]; then
    gdb -q $1 core -x ./backtrace
fi
```

to launch tests, please use script seg_wrapper.sh
```
./seg_wrapper.sh coverage run --source=src/onelogin/saml2 --rcfile=tests/coverage.rc setup.py test
```

PS:
need to add installation for gdb in your travis file.

**Comment by pitbulk** [comment]
Sorry for the delay.

Here is the info you requested:
https://travis-ci.org/onelogin/python3-saml/jobs/170436827

**Comment by bgaifullin** [comment]
@pitbulk Could you try this patch. https://github.com/bgaifullin/python-xmlsec/commit/0f046381ec6bac7b3dd8b2ad6da0d022e7b30274

And please add env variable: "CFLAGS='-Wall -O0 -g' " in travis file, this should help to display function names in stack trace instead of addresses.

**Comment by pitbulk** [comment]
I [targeted the last commit](https://github.com/onelogin/python3-saml/pull/31/files#diff-2eeaed663bd0d25b7e608891384b7298R39).

I added the env variable but it seems is not working since I see addresses no function names.

https://travis-ci.org/onelogin/python3-saml/jobs/173896434

**Comment by bgaifullin** [comment]
I see.
I will continue investigation, thank you @pitbulk

**Comment by pitbulk** [comment]
You can create in python-saml your own PR and apply any change you want on travis.

**Comment by bgaifullin** [comment]
I think about this, it would be better to create tests in python-xmlsec, which reproduces this fail.

**Comment by pitbulk** [comment]
@bgaifullin, Any progress with this issue?

**Comment by bgaifullin** [comment]
I was very busy last 2 month and actually I do not have idea how to resolve this issue unfortunately. 
I just recognised that this issue reproduces only with version of python from travis-ci.

**Comment by bgaifullin** [comment]
@pitbulk  I rewrote full library on pure C #37. this will help to resolve all issues related to versions of python, libxmlsec1 and other system libraries.

unfortunately I do not have time to run pyhton3-saml with the new version.  Could you help with this.

**Comment by pitbulk** [comment]
@bgaifullin your xmlsec branch mentions version 1.0.1

I modified python3-saml with
```
    install_requires=[
        'isodate>=0.5.0',
        'xmlsec==1.0.1',
    ],
    dependency_links=['https://github.com/bgaifullin/python-xmlsec/tarball/master'],
```

but when running python setup.py install
```
Processing dependencies for python3-saml==1.2.3
Searching for xmlsec==1.0.1
Reading https://github.com/bgaifullin/python-xmlsec/tarball/master
Reading https://pypi.python.org/simple/xmlsec/
No local packages or download links found for xmlsec==1.0.1
error: Could not find suitable distribution for Requirement.parse('xmlsec==1.0.1')
```

**Comment by bgaifullin** [comment]
@pitbulk I install xmlsec, and python3-saml to virtualenv and runs python3-saml tests.

**Comment by pitbulk** [comment]
but how you installed your version of xmlsec?

**Comment by bgaifullin** [comment]
`{path to venv}/bin/pip install -e .`

**Comment by pitbulk** [comment]
That installed xmlsec-0.6.1, but not your version

**Comment by bgaifullin** [comment]
@pitbulk please provide full list of commands which are you used.
I invoked the following commands, step by step:
```bash

virtualenv -p python3.5 venv
git clone https://github.com/bgaifullin/python-xmlsec
cd python-xmlsec
../venv/bin/pip install -r requirements-test.txt
../venv/bin/pip install -e .
cd ..
git clone https://github.com/bgaifullin/python3-saml
cd python3-saml
../venv/bin/pip install -e .

```

**Comment by pitbulk** [comment]
Executing pip install -e . on python-xmlsec with python2.7.6 I got:
```
 x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DXMLSEC_CRYPTO=openssl -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T= -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1, -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.0.1 -DMODULE_DOC=Python bindings for the XML Security Library -I/usr/local/include/xmlsec1 -I/usr/include/libxml2 -I/home/pitbulk/Escritorio/test-xmlsec/venv/local/lib/python2.7/site-packages/lxml/includes -I/home/pitbulk/Escritorio/test-xmlsec/venv/local/lib/python2.7/site-packages/lxml -I/usr/include/python2.7 -c ./src/key.c -o build/temp.linux-x86_64-2.7/./src/key.o -g -std=c99 -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
    ./src/key.c: In function ‘PyXmlSec_KeyFromMemory’:
    ./src/key.c:117:5: error: implicit declaration of function ‘ERR_clear_error’ [-Werror=implicit-function-declaration]
         ERR_clear_error(); // clear ssl error
         ^
    cc1: some warnings being treated as errors
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

Command "/test-xmlsec/venv/bin/python -c "import setuptools, tokenize; __file__='/test-xmlsec/python-xmlsec/setup.py'; exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" develop --no-deps" failed with error code 1 in /test-xmlsec/python-xmlsec
```

**Comment by bgaifullin** [comment]
@pitbulk, Oh, I got it. thank you.

**Comment by bgaifullin** [comment]
@pitbulk I pushed new version to [bgaifullin/python-xmlsec](https://github.com/bgaifullin/python-xmlsec)

**Comment by pitbulk** [comment]
I installed successfully on python2.7.6 and python3.4 but when executing the python setup.py test I got:
```
func=xmlSecCryptoDLLoadLibrary:file=dl.c:line=445:obj=unknown:subj=crypto != NULL:error=100:assertion: 
Traceback (most recent call last):

  File "/test-xmlsec/venv/local/lib/python2.7/site-packages/setuptools/command/test.py", line 37, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/test-xmlsec/python3-saml/tests/src/OneLogin/saml2_tests/metadata_test.py", line 13, in <module>
    from onelogin.saml2.metadata import OneLogin_Saml2_Metadata
  File "/test-xmlsec/python3-saml/src/onelogin/saml2/metadata.py", line 17, in <module>
    from onelogin.saml2.utils import OneLogin_Saml2_Utils
  File "/test-xmlsec/python3-saml/src/onelogin/saml2/utils.py", line 23, in <module>
    import xmlsec
RuntimeError: unable to load default xmlsec-crypto library.
```

**Comment by bgaifullin** [comment]
@pitbulk do you have install xmlsec-openssl or other crypto library for xmlsec ? 
please provide output of the command `pkg-config --cflags xmlsec1`

**Comment by pitbulk** [comment]
pkg-config --cflags xmlsec1
-DXMLSEC_CRYPTO=\"openssl\" -DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_DL_LIBLTDL=1, -I/usr/local/include/xmlsec1 -I/usr/include/libxml2

**Comment by bgaifullin** [comment]
@pitbulk is library xmlsec-openssl installed?

**Comment by bgaifullin** [comment]
@pitbulk one more question, in what OS are you tested?

**Comment by pitbulk** [comment]
I'm using Ubuntu 14.04.4 LTS

**Comment by bgaifullin** [comment]
I tried on Ubuntu 14.04.5 LTS.
install the following packages.
```
apt-get install libxmlsec1-dev libxmlsec1-openssl pkg-config
```
pkg-config xmlsec1 output is:
```
-DXMLSEC_CRYPTO=\"openssl\" -D__XMLSEC_FUNCTION__=__FUNCTION__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_XKMS=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_OPENSSL_098=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/usr/include/libxml2 -I/usr/include/xmlsec1
```

the main difference between option `DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1`

Please check that path to library libxmlsec1-openssl.so is available.

this library shall be in directory /usr/lib/ 
check that all dependencies are satisfied:
`ldd {path to libxmlsec1-openssl.so}`

you can also check xmlsec libraries in cache.
`ldconfig -p | grep xmlsec`

**Comment by pitbulk** [comment]
those packages are installed.
and I have the /usr/lib/libxmlsec1-openssl.so

```
ldd /usr/lib/libxmlsec1-openssl.so
	linux-vdso.so.1 =>  (0x00007ffc2db00000)
	libcrypto.so.1.0.0 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.0 (0x00007f45ce5ba000)
	libxml2.so.2 => /usr/lib/x86_64-linux-gnu/libxml2.so.2 (0x00007f45ce253000)
	libxmlsec1.so.1 => /usr/local/lib/libxmlsec1.so.1 (0x00007f45cdfeb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f45cdc26000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f45cda22000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f45cd809000)
	liblzma.so.5 => /lib/x86_64-linux-gnu/liblzma.so.5 (0x00007f45cd5e7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f45cd2e1000)
	libxslt.so.1 => /usr/lib/x86_64-linux-gnu/libxslt.so.1 (0x00007f45cd0a4000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f45cce9a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f45cebcd000)
```

```
ldconfig -p | grep xmlsec
	libxmlsec1.so.1 (libc6,x86-64) => /usr/local/lib/libxmlsec1.so.1
	libxmlsec1.so.1 (libc6,x86-64) => /usr/lib/libxmlsec1.so.1
	libxmlsec1.so (libc6,x86-64) => /usr/local/lib/libxmlsec1.so
	libxmlsec1.so (libc6,x86-64) => /usr/lib/libxmlsec1.so
	libxmlsec1-openssl.so.1 (libc6,x86-64) => /usr/local/lib/libxmlsec1-openssl.so.1
	libxmlsec1-openssl.so.1 (libc6,x86-64) => /usr/lib/libxmlsec1-openssl.so.1
	libxmlsec1-openssl.so (libc6,x86-64) => /usr/local/lib/libxmlsec1-openssl.so
	libxmlsec1-openssl.so (libc6,x86-64) => /usr/lib/libxmlsec1-openssl.so
	libxmlsec1-nss.so.1 (libc6,x86-64) => /usr/local/lib/libxmlsec1-nss.so.1
	libxmlsec1-nss.so.1 (libc6,x86-64) => /usr/lib/libxmlsec1-nss.so.1
	libxmlsec1-nss.so (libc6,x86-64) => /usr/local/lib/libxmlsec1-nss.so
	libxmlsec1-nss.so (libc6,x86-64) => /usr/lib/libxmlsec1-nss.so
	libxmlsec1-gnutls.so.1 (libc6,x86-64) => /usr/local/lib/libxmlsec1-gnutls.so.1
	libxmlsec1-gnutls.so.1 (libc6,x86-64) => /usr/lib/libxmlsec1-gnutls.so.1
	libxmlsec1-gnutls.so (libc6,x86-64) => /usr/local/lib/libxmlsec1-gnutls.so
	libxmlsec1-gnutls.so (libc6,x86-64) => /usr/lib/libxmlsec1-gnutls.so
	libxmlsec1-gcrypt.so.1 (libc6,x86-64) => /usr/local/lib/libxmlsec1-gcrypt.so.1
	libxmlsec1-gcrypt.so.1 (libc6,x86-64) => /usr/lib/libxmlsec1-gcrypt.so.1
	libxmlsec1-gcrypt.so (libc6,x86-64) => /usr/local/lib/libxmlsec1-gcrypt.so
	libxmlsec1-gcrypt.so (libc6,x86-64) => /usr/lib/libxmlsec1-gcrypt.so
```

On that machine was working the other version of python-xmlsec library so I'm lost why there is a xmlsec issue.

**Comment by bgaifullin** [comment]
@pitbulk There is 2 installation of libxmlsec1.
One of in directory /usr/lib, and another in directory /usr/local/lib

Could you remove them and install the libxmlsec1 from scratch?

**Comment by pitbulk** [comment]
I will test in a fresh laptop, right now no idea how I installed /usr/local/lib/libxmlsec1 so don't know if removing it will break something.

**Comment by pitbulk** [comment]
On a fresh machine that uses python3.5 I was able to execute the test pn python3-saml, but got a segmentation fault.

This is what I got:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00000000004a7ee4 in ?? ()
#0  0x00000000004a7ee4 in ?? ()
#1  0x00000000004a7fc9 in ?? ()
#2  0x00000000004a70e7 in ?? ()
#3  0x000000000050102e in PyGC_Collect ()
#4  0x0000000000500484 in Py_Finalize ()
#5  0x000000000049df2f in Py_Main ()
#6  0x00007fa3b01ff830 in __libc_start_main (main=0x49dab0 <main>, argc=3, argv=0x7ffce71a1c78, init=<optimized out>, fini=<optimized out>,
    rtld_fini=<optimized out>, stack_end=0x7ffce71a1c68) at ../csu/libc-start.c:291
#7  0x000000000049d9d9 in _start ()
```

**Comment by bgaifullin** [comment]
@pitbulk, thank you for help, I will investigate this.

**Comment by pitbulk** [comment]
let me know if you want me to try anything, now that we are able to reproduce the issue on a local machine ;)

**Comment by bgaifullin** [comment]
Hi.
there is ci, which passes on latest commit from python-xmlsec.
https://travis-ci.org/bgaifullin/python3-saml/builds/196381841
There is only one problem, I used ubuntu:trusty for python3.5, since
version of libxml2 which provides by ubuntu-precise do not work with
python3.5. there is issue with memory allocation in libxml2 and I do not
know how to fix it.

Travis currently allows to use ubuntu - trusty.
https://docs.travis-ci.com/user/trusty-ci-environment#Using-Trusty



2017-01-23 22:36 GMT+03:00 Sixto Martin <notifications@github.com>:

**Comment by pitbulk** [comment]
Hi @bgaifullin 

I installed your version of python3-saml and last version of python-xmlsec and test pass on python3-saml for python and python3 ;)

**Comment by bgaifullin** [comment]
Hi @pitbulk , many thanks for your help with testing.

**Comment by bgaifullin** [comment]
I think the issue can be closed.
I have updated README.md with minimal required versions of libxml2 and libxmlsec1, also I added instructions how to install python-xmlsec on ubuntu:precise.
