### ISSUE TITLE
Can you test if the builds/tests fail now on Travis?

### ISSUE THREAD

**Issue by pitbulk** [mehcode/python-xmlsec#30]
At [python3-saml](https://github.com/onelogin/python3-saml) I experienced that Travis fails with
python 2.7.12, 3.3.5, 3.3.6, 3.4.3, 3.5.0

```
home/travis/build.sh: line 45:  6316 Segmentation fault      (core dumped)
```

I wonder if you can run travis and see if you experience a similar issue on python-xmlsec.

**Comment by pitbulk** [comment]
ping!

**Comment by bgaifullin** [comment]
I hope the issue with travis was resolved. to run tests on ubuntu:precise need to install libxml2 manually or need to use ubuntu:trusty image with travis:ci, there is instructions how to switch on ubuntu:trusty. https://docs.travis-ci.com/user/trusty-ci-environment/#Using-Trusty
