### ISSUE TITLE
PIP install raises error with python 3.4

### ISSUE THREAD

**Issue by danielkalenda** [mehcode/python-xmlsec#54]
first error here:
```
creating build/temp.macosx-10.6-intel-3.4/src
  /usr/bin/clang -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch i386 -arch x86_64 -g -DMODULE_DOC=Python bindings for the XML Security Library -DMODULE_NAME=xmlsec -DMODULE_VERSION=1.0.1 -I/Users/musecom/bspotted/lib/python3.4/site-packages/lxml/includes -I/Users/musecom/bspotted/lib/python3.4/site-packages/lxml/includes/__pycache__ -I/Users/musecom/bspotted/lib/python3.4/site-packages/lxml -I/Library/Frameworks/Python.framework/Versions/3.4/include/python3.4m -c ./src/constants.c -o build/temp.macosx-10.6-intel-3.4/./src/constants.o -g -std=c99 -fno-strict-aliasing -Wno-error=declaration-after-statement -Werror=implicit-function-declaration -Os
  In file included from ./src/constants.c:11:
  In file included from ./src/constants.h:13:
  ./src/platform.h:15:10: fatal error: 'xmlsec/version.h' file not found
  #include <xmlsec/version.h>
```

second error

`bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/mq/s81xm_kn23n4_kk79z5f25gr0000gq/T/pip-rms9723j-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/mq/s81xm_kn23n4_kk79z5f25gr0000gq/T/pip-siiwo1qp-record/install-record.txt --single-version-externally-managed --compile --install-headers /Users/musecom/bspotted/bin/../include/site/python3.4/xmlsec" failed with error code 1 in /private/var/folders/mq/s81xm_kn23n4_kk79z5f25gr0000gq/T/pip-rms9723j-build/`
`

**Comment by bgaifullin** [comment]
Hi @danielkalenda 
Do you install all requirements from README, libxml2-dev libxmlsec1-dev libxmlsec1-openssl ? 
There is no way to specify this requirements in pip, because it depends on OS and package manager which is default for OS.

**Comment by bgaifullin** [comment]
also please attach the output of command `pkg-config --cflags xmlsec1`

**Comment by bgaifullin** [comment]
@danielkalenda, do you still need help?

**Comment by danielkalenda** [comment]
@bgaifullin Thanks it appears the libs were missing! Cheers Daniel

**Comment by bgaifullin** [comment]
@danielkalenda, you are welcome.
I will close the issue.
