### ISSUE TITLE
Add support for xmlSecTmplTransformAddC14NInclNamespaces

### ISSUE THREAD

**Issue by neoecos** [mehcode/python-xmlsec#59]
Hi,

For consuming a SOAP WebService with required Signature, the Transform should contain a InclusiveNamespaces tag, as defined in the EXC_C14.

Those call aren't implemente yet in the python-xmlsec wrapper.

**Comment by bgaifullin** [comment]
Released in version 1.0.9

**Comment by bgaifullin** [comment]
http://pythonhosted.org/xmlsec/modules/template.html#xmlsec.template.transform_add_c14n_inclusive_namespaces
