### ISSUE TITLE
Missing tag for 0.6.1

### ISSUE THREAD

**Issue by rouge8** [mehcode/python-xmlsec#62]
It'd be helpful to have tags on GitHub for all of the PyPI releases if possible. We're unable to use 1.0.x because of memory leaks (working on a minimal example for a separate issue). In the meantime, there's a tag for 0.6.0 on GitHub, but a 0.6.1 release on PyPI.

**Comment by bgaifullin** [comment]
@rouge8 if I create tag for version 0.6.1  the chronology of tags will be broken. I prefer to avoid this, 
it would be great if you switch to version 1.0.x. I will help you to do this. 
It would be great if you provide minimal example for memory leaks. it would be really helpful.

**Comment by bgaifullin** [comment]
the version 0.6.1 was release from commit d7feedf241b5fc034cff1f1b46248bb9ed0cef55

**Comment by bgaifullin** [comment]
I can create branch for version 0.6.1, does it work for you ?

**Comment by rouge8** [comment]
@bgaifullin as long as you don't create a release (just a tag), the chronology should be fine, e.g. https://github.com/rouge8/python-xmlsec/releases

**Comment by bgaifullin** [comment]
@rouge8  I mean chronology of tags https://github.com/mehcode/python-xmlsec/tags

**Comment by rouge8** [comment]
Sure, and adding 0.6.1 shows up on July 5, 2016:
https://github.com/rouge8/python-xmlsec/tags

**Comment by bgaifullin** [comment]
O, I do not know about this. Thank you :)

**Comment by bgaifullin** [comment]
@rouge8 How you do this, when I creating tag, it becames at top position.

**Comment by bgaifullin** [comment]
@rouge8 done. I have created tag 0.6.1, thank you for help.
