### ISSUE TITLE
ImportError: No module named 'xmlsec_setupinfo'

### ISSUE THREAD

**Issue by marcus-ahle** [mehcode/python-xmlsec#70]
We're receiving the following error when attempting to pip install xmlsec 1.3.2.
```
09:54:23   Downloading xmlsec-1.3.2.tar.gz
09:54:23     Complete output from command python setup.py egg_info:
09:54:23     Traceback (most recent call last):
09:54:23       File "<string>", line 1, in <module>
09:54:23       File "/tmp/pip-build-asinjmj6/xmlsec/setup.py", line 5, in <module>
09:54:23         import xmlsec_setupinfo
09:54:23     ImportError: No module named 'xmlsec_setupinfo'
```
Looks like xmlsec_setupinfo.py isn't getting packaged up in the tar: https://pypi.python.org/packages/57/2e/fd42a79472c19b7c01ead43ab3c2120554234441848ac790f9839993443e/xmlsec-1.3.2.tar.gz#md5=37b14968a0ef150455a4e9d2dd4149fe

**Comment by bgaifullin** [comment]
It is fixed. I just need to release new version.

**Comment by bgaifullin** [comment]
version 1.3.3 is released.
I apologize for the reasons for the inconvenience.
