### ISSUE TITLE
Check that package correctness before upload to pip

### ISSUE THREAD

**Issue by bgaifullin** [mehcode/python-xmlsec#71]
Version 1.3.2 was broken and CI did not recognise this.
Need to add tests to make sure that package is correct, before uploading to PIP.

**Comment by jtojnar** [comment]
This is also relevant for Linux distributions packaging python modules from PyPI; see also the Debian thread about the issue:
https://lists.debian.org/debian-python/2016/04/msg00074.html

**Comment by hoefling** [comment]
Both GH Actions, Appveyor and Travis now use the same strategy: build the wheel/source dist, install from wheel/source dist, run tests. This should be enough to ensure both sdists and wheels uploaded to PyPI are sane.
