### ISSUE TITLE
Value error during pip install

### ISSUE THREAD

**Issue by dangerm0us** [mehcode/python-xmlsec#73]
Hi, I get this error when installing xmlsec via pip:

"        raise ValueError("path '%s' cannot be absolute" % pathname)
    ValueError: path '/home/travis/build/mehcode/python-xmlsec/src/constants.c'
cannot be absolute"

Environment:

Windows 2008 R2 Server
Python 3.5
lmxl v4.1.1

Any clues?  Thank you.

**Comment by bgaifullin** [comment]
Hi. There is prebuilt binaries for windows on appveyour, you can check readme for details

**Comment by hoefling** [comment]
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.
