### ISSUE TITLE
Problem installing xmlsec on Mac 10.13.4, version 1.3.3

### ISSUE THREAD

**Issue by nguyenkims** [mehcode/python-xmlsec#80]
I have this error when trying to import `xmlsec` `python -c "import xmlsec"`

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python3.6/site-packages/xmlsec.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libcrypto.1.0.0.dylib
  Referenced from: /usr/local/lib/python3.6/site-packages/xmlsec.cpython-36m-darwin.so
  Reason: image not found
```

The lib seems to work fine when installing from the last master branch though:

> pip install .
> python -c "import xmlsec; print(xmlsec.__version__)"

that gives `1.0.1.dev0` as output. By the way, the master version `1.0.1.dev0` is supposed to be newer than the pypi version `1.3.3` which doesn't seem to be the case.  

Below is my system information:

Mac 10.13.4
Python 3.6.5 installed with brew
libxmlsec1: stable 1.2.25 (bottled): installed with brew
libxml2: stable 2.9.7 (bottled), HEAD [keg-only]: installer with brew

Output of `pkg-config --cflags xmlsec1`

```
-D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1 -DXMLSEC_CRYPTO_OPENSSL=1 -I/usr/local/Cellar/libxmlsec1/1.2.25/include/xmlsec1 -I/usr/local/opt/openssl/include -I/usr/include/libxml2
```

**Comment by bgaifullin** [comment]
seem like there is error with libcrypro. 
do you install openssl with brew and add libcrypto location folder into LD_LIBRARY_PATH ?

**Comment by malthejorgensen** [comment]
### Solution

Also using `homebrew` on OS X here, and had the same error.

I was able to get it to work by installing python-xmlsec like this:

    pip install xmlsec --global-option=build_ext --global-option="-I/usr/local/opt/openssl@1.1/include"

### Debugging

If you're getting this error it's seems to be because `xmlsec.*.so` is linked to `libcrypto.1.0.0.dylib`, and you don't have that installed -- you have probably `libcrypto.1.1.dylib` installed. You can check what `xmlsec.*.so` is linked against like this:

```
otool -L<path_to_venv>/.venv/lib/python3.7/site-packages/xmlsec.cpython-37m-darwin.so
	/usr/local/opt/libxmlsec1/lib/libxmlsec1-openssl.1.dylib (compatibility version 4.0.0, current version 4.29.0)
	/usr/local/opt/libxmlsec1/lib/libxmlsec1.1.dylib (compatibility version 4.0.0, current version 4.29.0)
# WRONG /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
# RIGHT /usr/local/opt/openssl@1.1/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libxslt.1.dylib (compatibility version 3.0.0, current version 3.26.0)
	/usr/lib/libxml2.2.dylib (compatibility version 10.0.0, current version 10.9.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
	/usr/lib/libicucore.A.dylib (compatibility version 1.0.0, current version 57.1.0)
```

of course only one `libcrypto.*.dylib` will show in the output, and in some cases the right one is `libcrypto.1.0.0.dylib` (on older homebrew etc.)

**Comment by hoefling** [comment]
`brew info openssl` lists all the necessary configuration steps:

```sh
$ brew info openssl

...

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

However, I can't reproduce this issue on 10.15.5 anymore when building against brewed `openssl` and `xmlsec1`, everything should work out as expected:

```sh
$ brew install openssl xmlsec1

...

$ pkg-config --cflags xmlsec1
-D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1
-DXMLSEC_NO_GOST2012=1 -DXMLSEC_NO_CRYPTO_DYNAMIC_LOADING=1
-DXMLSEC_CRYPTO_OPENSSL=1 -I/usr/local/Cellar/libxmlsec1/1.2.30/include/xmlsec1
-I/usr/local/opt/openssl@1.1/include -I/usr/local/opt/openssl@1.1/include/openssl
$ pkg-config --libs xmlsec1
-L/usr/local/Cellar/libxmlsec1/1.2.30/lib -L/usr/local/opt/openssl@1.1/lib -lxmlsec1-openssl
-lxmlsec1 -lcrypto -lxslt -lxml2 -lz -lpthread -licucore -lm -lxml2
```
