### ISSUE TITLE
windows binaries will be removed on 17th June 2018 from ci.appveyor.com

### ISSUE THREAD

**Issue by bgaifullin** [mehcode/python-xmlsec#82]
Subj, need to find other place to host this binaries.

**Comment by utek** [comment]
Hi. Any update on this issue? As those binaries are already deleted.

**Comment by Mause** [comment]
They should be published to pypi instead?

**Comment by bgaifullin** [comment]
publish windows binaries in github. 
I do not find any way to publish those binaries in pypi. (

**Comment by Mause** [comment]
They should be published to pypi so that they can be installed automatically via pip?

**Comment by hoefling** [comment]
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.
