### ISSUE TITLE
windows wheel files not available

### ISSUE THREAD

**Issue by plasticav** [mehcode/python-xmlsec#85]
I'm trying to install zeep[xmlsec] on a windows system with Python 3.6. It results in the following,

```
Installing collected packages: xmlsec
  Running setup.py install for xmlsec: started
    Running setup.py install for xmlsec: finished with status 'error'
    Complete output from command D:\home\python364x64\python.exe -u -c "import setuptools, tokenize;__file__='D:\\local\\Temp\\pip-install-l510dnt_\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record D:\local\Temp\pip-record-p1y7cdcl\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Retrieving "https://ci.appveyor.com/api/buildjobs/hij3a6776pdv2007/artifacts/libxml2-2.9.4.win64.zip" to "build/extra\libxml2-2.9.4.win64.zip"
    error: HTTP Error 404: The specified blob does not exist.
    
    ----------------------------------------

```

to what I can tell, it looks like the libxml and xmlsec wheel files were hosted on appveyor, but they don't have them anymore. Can we please get them hosted again?

related install attempt,

```
D:\home\site\wwwroot>D:\home\python364x64\pip.bat install xmlsec
Collecting xmlsec
  Using cached https://files.pythonhosted.org/packages/35/42/d7cd323c91d4706f3cc32ffe7d5f851ab8ef9898ccb350f6ba593dd8b89a/xmlsec-1.3.3.tar.gz
Requirement already satisfied: pkgconfig in d:\home\python364x64\lib\site-packages (from xmlsec)
Requirement already satisfied: lxml>=3.0 in d:\home\python364x64\lib\site-packages (from xmlsec)
Installing collected packages: xmlsec
  Running setup.py install for xmlsec: started
    Running setup.py install for xmlsec: finished with status 'error'
    Complete output from command D:\home\python364x64\python.exe -u -c "import setuptools, tokenize;__file__='D:\\local\\Temp\\pip-build-_75yc_6u\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record D:\local\Temp\pip-y7wv7xut-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    Retrieving "https://ci.appveyor.com/api/buildjobs/hij3a6776pdv2007/artifacts/libxml2-2.9.4.win64.zip" to "build/extra\libxml2-2.9.4.win64.zip"
    error: HTTP Error 404: The specified blob does not exist.
    
    ----------------------------------------
Command "D:\home\python364x64\python.exe -u -c "import setuptools, tokenize;__file__='D:\\local\\Temp\\pip-build-_75yc_6u\\xmlsec\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record D:\local\Temp\pip-y7wv7xut-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in D:\local\Temp\pip-build-_75yc_6u\xmlsec\
You are using pip version 9.0.1, however version 18.0 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

D:\home\site\wwwroot>
```

**Comment by bgaifullin** [comment]
the appveyour changes its policy about retention build artifacts.
if someone knows where this files may be posted instead of appveyour - welcome.
I cannot just rebuild projects since build rules have been changed and build fails.
I anyone can fix this, please make PR for repository https://github.com/bgaifullin/libxml2-win-binaries.

**Comment by plasticav** [comment]
@bgaifullin  if the issue is hosting, can we consider using github releases for the wheel files?

**Comment by plasticav** [comment]
Alternatively, has pythonhosted.org been considered?

https://packaging.python.org/tutorials/packaging-projects/

**Comment by bgaifullin** [comment]
@plasticav the github releases can be used, but need to change scripts for uploading into github after build. Can you do this? 
about pythonhosted.org, there is libxml2 binaries for windows, and I am not sure, that it can be hosted on pythonhosted.org.

**Comment by covelloz** [comment]
Not only the wheel. The pip build (pip install xmlsec) and manual install (python setup.py install) options do not work either.

Getting the following error:

```
zipfile.BadZipfile: File is not a zip file
```

You can see this is the same error in the wheel's build too:
https://ci.appveyor.com/project/bgaifullin/python-xmlsec/build/job/ed6uyd5t68gscyv3

**Comment by thewebkid** [comment]
This issue is not resolved. This is a circular issue reference if you read to the bottom of 35. It is currently a big blocker for me.

**Comment by bgaifullin** [comment]
the latest windows binaries are available here https://github.com/mehcode/python-xmlsec/releases/tag/1.3.5

**Comment by ing200086** [comment]
Any movement on this? I am getting the same issue. On python 2.7 I get a badzip error, and on python 3.7 I get ci.appveyor.com is no longer available.

**Comment by RSwarnkar** [comment]
Hi there, I don't see any release for `Python 3.7.x` environment on windows. Can you please please make a release?  Tried with Python 3.6 release did not worked: 

`ERROR: xmlsec-1.3.52.dev0-cp36-cp36m-win_amd64.whl is not a supported wheel on this platform.
`

**Comment by neemzy** [comment]
Same demand and issue as @RSwarnkar; installing the 32-bit binary worked, though.

**Comment by klatessa** [comment]
@neemzy Which one did you get to install. I have gone through all of them and get "not a supported wheel on this platform"

**Comment by neemzy** [comment]
@klatessa `xmlsec-1.3.52.dev0-cp36-cp36m-win32.whl`

**Comment by majvan** [comment]
@neemzy : the win32 wheel package not work for me for python 3.7

**Comment by hoefling** [comment]
@majvan try

```sh
pip install xmlsec --extra-index-url=https://hoefling.io/pypi
```

I will upload wheels for windows on PyPI soon, with the release of 1.3.7.
