### ISSUE TITLE
Option to avoid line breaks in base64 (xmlSecBase64SetDefaultLineSize)

### ISSUE THREAD

**Issue by r03** [mehcode/python-xmlsec#95]
I had a problem where a signature breaks because of line breaks.
(this shouldn't fail, but I'm using an external service that I can't change)

The solution is found here:
https://www.aleksey.com/pipermail/xmlsec/2010/008921.html

For testing I added this in function `PyXmlSec_Init` (main.c):
`xmlSecBase64SetDefaultLineSize(0);`
and added this include
`#include <xmlsec/base64.h>`

This works for me.

Maybe this could be an option in python-xmlsec?

**Comment by hoefling** [comment]
@r03 I like this suggestion. The linked PR adds a new function `xmlsec.base64_line_size()`:

```python

import xmlsec

# get the current setting
current_size = xmlsec.base64_line_size()

# set new size
xmlsec.base64_line_size(0)
```
It'll be great if you can try out installing from the PR branch and confirming it works as intended!

**Comment by r03** [comment]
Sorry. I’m no longer working on that project (it’s finished) and can’t really test. But your fix looks nice. Thanks!!
