### ISSUE TITLE
Compile against locally installed version

### ISSUE THREAD

**Issue by AvnerCohen** [mehcode/python-xmlsec#97]
Apologies if I am missing something obvious, couldn't find any solution in the existing issues.

On my CentsOs 7, I have xmlsec1.2.20 installed, I wanted this updated to latest version - 1.2.27
This meant download the code and run `make && make install`

I have updated the pkg_config env variable so result of `pkg-config --cflags xmlsec1` is now:
```
-DXMLSEC_CRYPTO_DYNAMIC_LOADING=1 -D__XMLSEC_FUNCTION__=__func__ -DXMLSEC_NO_SIZE_T -DXMLSEC_NO_GOST=1 -DXMLSEC_NO_GOST2012=1 -DXMLSEC_DL_LIBLTDL=1 -I/usr/local/include/xmlsec1 -I/usr/include/libxml2
``
usr/local/include/xmlsec1 is indeed the update code.

When actually importing code (in suds) I get the following error:
```
>>> from hs_workday_connector.wsse_workday.suds import WssePlugin
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "**/suds.py", line 4, in <module>
    from .signing import sign
  File "**/signing.py", line 12, in <module>
    import xmlsec
ImportError: ***/lib/python2.7/site-packages/xmlsec.so: undefined symbol: xmlSecGetDefaultCrypto
```

Any ideas what I am doing wrong?

**Comment by hoefling** [comment]
This is not a `python-xmlsec` issue and indicates an improper build of `libxmlsec1`. Unset `PKG_CONFIG_PATH`, run `pkg-config --cflags xmlsec1` to record the flags the packaged `libxmlsec1` was built with. Now set `PKG_CONFIG_PATH` again, print the flags your local copy of `libxmlsec1` was built with and compare for differences.

Other than that, I'd really not to dig into build issues of `libxmlsec1` or `libxml2` or any other dependency. If you encounter errors you can't resolve, you can always build a static wheel thta bundles all the necessary symbols in a fat shared object. See https://github.com/mehcode/python-xmlsec/issues/81#issuecomment-633230184 for details.
