### ISSUE TITLE
build fails with python37 on windows 10

### ISSUE THREAD

**Issue by snehm** [mehcode/python-xmlsec#98]
Please upload wheel file for python37 - amd64.

**Comment by snehm** [comment]
`fatal error C1047: The object or library file 'build\extra\iconv-1.14.win64\lib\iconv_a.lib' was created with an older compiler than other objects; rebuild old objects and libraries
LINK : fatal error LNK1257: code generation failed`

**Comment by fabiopedrosa** [comment]
can someone upload the wheel?

**Comment by talebi1** [comment]
created a pull request to fix the issue https://github.com/mehcode/python-xmlsec/pull/116

The issue was that 3rd-party dependencies were compiled with an old version of visual studio, so I recompiled them with vs2017 (available here https://github.com/talebi1/libxml2-win-binaries/releases/tag/master)

Until the pull request is merged, you can:

```
git clone https://github.com/talebi1/python-xmlsec.git
cd python-xmlsec
pip install .

```

**Comment by fabiopedrosa** [comment]
@talebi1 
Still can't compile it under my windows dev environment. Can you write a brief summary of what I'd need to install on a fresh win10 machine to get the wheels?

I have VS2017 with python extensions.

**Comment by fabiopedrosa** [comment]
@talebi1 you can see here how its failing for win64 but not win32: https://ci.appveyor.com/project/fabiopedrosa/python-xmlsec

**Comment by robbo4** [comment]
> git clone https://github.com/talebi1/python-xmlsec.git
> cd python-xmlsec
> pip install .

I tried this but no luck. Any ideas when a wheel might be available for x64?

**Comment by hoefling** [comment]
Repeating my comment from [here](https://github.com/onelogin/python3-saml/issues/110#issuecomment-619646313):

> I have built windows wheels for `xmlsec`. Add my PyPI index when installing:
> 
> ```sh
> pip install python3-saml --extra-index-url=https://hoefling.io/pypi
> ```
> I will prepare a PR for `xmlsec` that resolves the issue with windows wheels. In the meantime, passing additional index should be good enough for a workaround. See also [my answer on SO](https://stackoverflow.com/a/61449322/2650249) for more details.

**Comment by hoefling** [comment]
A new version 1.3.7 [was released today](https://pypi.org/project/xmlsec/1.3.7/). One of the notable changes includes pushing prebuilt wheels for Windows on PyPI, so the issue with building Windows wheels locally should be resolved. Install as usual:

```sh
pip install xmlsec
```

Should you experience any issues with prebuilt wheels on Windows, please don't hesitate to open a new issue.
